remote_theme: just-the-docs/just-the-docs
title: Page Test Documentation
description: A documentation site with LaTeX support and navigation
markdown: kramdown
math: katex
color_scheme: dark
aux_links:
  "View on GitHub":
    - "//github.com/gyu-heo/test_pages"

# Enable automatic ToC
toc:
  enabled: true
  h_min: 2
  h_max: 3
